**1. What does one need to do to use a module?** 

-  Use the import statement

**2. Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.**

- Math Module
- import math as mp
- print(mp.sqrt(3.14))

**3. What is a benefit of using Exception handling?**

- The benefit is you can test code and it will run the code past any errors.

**4. NumPy arrays are like what Python data type?**

- List or a lsit within a list

**5. What is one of the main benefits of using NumPy arrays.**

- Uses less memory

**6. What is one of the main requirements about the 'dtype' of NumPy arrays?**

- Data type must be the dame

**7. Of the 10 uses of NumPy, name 2.**

- Statistics, sorting, and counting

**8. Name one of the other libraries we will use with NumPy?**

- Panda

**9. What is the shape of NumPy arrays?**

- dimension is the length and size of each array

**10. What is a Tensor?**

- An array with three dimensions

**11. Name a reason why it is better using NumPy for Data Analysis than using a Python List?**

- Consumes less memory

**12. When creating an "empty" array, where do the elements come from?**

- Contents are random and depends on size of memory

**13. What does Pandas stand for?**

- Panel Data

**14. What are the 2 collections used in Pandas?**

- Dataframes and series I guess

**15. Name 4 things Pandas can do for us.**

- Data cleansing
- Statistical analysis
- Data visualization
- Merges and joins

**16. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?**

- inplace = True

**17. What is a CSV?**

- A plain text file separated by commas

**18. When cleaning data what values do we not like in our data?**

- Null Values


In [6]:
import math as mp
print(mp.sqrt(3.14))

1.772004514666935


In [ ]:
import numpy as np
# Arrays
arraya = ([[25, 16]])
arrayb = ([[11, 2], [13, 4]])
arrayc = ([[7, 81], [5, 6], [11, 12]])

# 1. Concatenate arrays
newArray = np.concatenate((arraya, arrayb, arrayc),)
print(newArray)

# 2.Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)
print(sortedArray)

# 3. Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
reshapedArray = sortedArray.reshape(2,2,3)
print(reshapedArray)




In [28]:
# 4. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

Tup1, Tup2 = reshapedArray

a, b = Tup1
c, d = Tup2

print(a)
print(b)
print(c)
print(d)
#5. Combine and sort the following arrays into one called 'comboArray' ...

import numpy as np

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate(((one, two, three)))
comboArray2 = np.sort(comboArray)
print(comboArray2)

[16 25  2]
[11  4 13]
[ 7 81  5]
[ 6 11 12]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [38]:
#6Take 'comboArray' and perform the following slicing activities:
        # print sec1 - the 2nd element
        # print sec2 - all elements from the 3rd element to the last
        # print sec3 - all elements from the 4th to the 14th elements
        # print sec4 - the last 6 elements
        # print sec5 - all element from #0 up to and including #15, using the negative number method, 
                # i.e. taking a section from the end.
        # print sec6 - from #20 every even element to the end
        # print sec7 - from the last element moving forward, every 5th element.
        
print(len(comboArray2))

sec1 = comboArray2[2]
print(sec1)

sec2 = comboArray2[3:24]
print(sec2)

sec3 = comboArray2[4:15]
print(sec3)

sec4 = comboArray2[-6:]
print(sec4)

sec5 = (comboArray2[-24:-10])
print(sec5)

sec6 = comboArray2[16:25:2]
print(sec6)

sec7 = comboArray2[::-5]
print(sec7)

24
2
[ 3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 4  5  6  7 10 11 12 13 14 15 16]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [42]:
# 7. Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --

import numpy as np

Array1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

Array2 = np.array([[17.0, 70.0, 10.7]])

Addition = np.add(Array1, Array2)
print(Addition)

Division = np.divide(Array1, Array2)
print(Division)

Multiplication = np.multiply(Array1, Array2)
print(Multiplication)
# 8. Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in point #7.

Subtraction = np.subtract(Array1, Array2)
print(Subtraction)

# 9. Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.

Divisible3 = Array1[Array1 % 3 == 0]
print(Divisible3)


[[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
[[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]
[[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]
[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]
[ 0.  0. 30. 24. 15.]


In [52]:
# 10. Using Series, create a DataFrame that looks like this:
#Ingredients	Quantity	Unit
#Flour	4	cups
#Milk	1	cup
#Eggs	2	large
#Spam	1	can
#Name: Dinner, dtype: object

import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name= 'ingredients')
quantity = pd.Series([4,1,2,1], name= 'quantity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name= 'unit')

index_labels = ["Index 1", "Index 2", "Index 3", "Index 4"]
ingredients.index = index_labels
quantity.index = index_labels
unit.index = index_labels

Dinner = pd.concat([ingredients,quantity,unit], axis=1)
print(Dinner)


        ingredients  quantity   unit
Index 1       Flour         4   cups
Index 2        Milk         1    cup
Index 3        Eggs         2  large
Index 4        Spam         1    can


In [60]:
# 11. Take this data and create a DataFrame named studentData

import pandas as pd

data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }

studentData = pd.DataFrame(data)
print(studentData)

# 12. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData.insert(7, "Deserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], True)
print("\n", studentData)

# 13. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name'], inplace = True)
print(studentData)

studentData.sort_values(by = ['address'], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  
      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot      

In [85]:
#14. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

import pandas as pd

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')
df_saved_file = pd.read_csv('cows_and_goats.csv')

In [84]:
# 15. 
    # (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
    # (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
    
import pandas as pd

df = pd.DataFrame({'Vegetables': ['tomatos', 'onion'], 'Vegetables2': ['squash','carrots']}, index=[1, 2])

df.to_csv('vegetables.csv')
df_saved_file = pd.read_csv('vegetables.csv')

df1 = df.replace(to_replace={'squash': 'spinach'})
print(df1)

df1.to_csv('newvegetables.csv')
df_saved_file = pd.read_csv('newvegetables.csv')

  Vegetables Vegetables2
1    tomatos     spinach
2      onion     carrots
